### ISSUE TITLE
Missing pip

### ISSUE THREAD

**Issue by giumas** [CCOMJHC/VBI-Compare#1]
In the [Install QGIS Using the OSGeo4W Installer](https://github.com/CCOMJHC/VBI-Compare#install-qgis-using-the-osgeo4w-installer) section of the [readme](https://github.com/CCOMJHC/VBI-Compare#readme), it should be mentioned to also install `python3-pip`.

**Comment by pdebroisse** [comment]
For the development of the program, we are not using pip. Could you describe the issue you ran into with this?

**Comment by giumas** [comment]
By following the directions in https://github.com/CCOMJHC/VBI-Compare#usage , there is a required step of running: python -m **pip** install boto3

**Comment by pdebroisse** [comment]
Updated and pushed. Thank you for catching that.
