### ISSUE TITLE
App crashes for invalid folder path

### ISSUE THREAD

**Issue by giumas** [CCOMJHC/VBI-Compare#2]
The app crashes when it attempts to create a folder with a space -> 'C:\\code\\ccomjhc\\output\\dcdb\\LI \\Archive':

![cmd_7h0xSAJe6z](https://github.com/CCOMJHC/VBI-Compare/assets/2849257/ace7dd4b-8ad0-42ed-8de4-5174878c8e87)

**Comment by pdebroisse** [comment]
Thank you. I'm looking into this. More to come.

**Comment by pdebroisse** [comment]
Trailing space issue should be fixed using rstrip(). I also asked DCDB if this was an accidental character or if it is intended to be there for future reference.
